<directory name="deepin-pygtk" rev="6" srcmd5="7db18cf21ea17a48cee5280e0b52c43d" vrev="6">
  <serviceinfo code="succeeded" xsrcmd5="b4ae26bd898e7c7b115140ce1ac18607" />
  <entry md5="b05fe7773cec550c053f511fcb193c49" mtime="1404663917" name="PKGBUILD" size="1772" />
  <entry md5="f05ac619cb41aaa82c250074ff51dbb3" mtime="1404663917" name="_service" size="245" />
  <entry md5="996dbf3f9080c6703c7f79d1b6e48ef9" mtime="1397597447" name="pygtk_2.24.0-4~saucy.debian.tar.gz" size="16830" />
  <entry md5="12acfacd26f19c504a0a2d0edeb66121" mtime="1397596775" name="python27.patch" size="1533" />
</directory>
